check50:
  checks:
    calender:
      - run: python3 calender.py
        stdin: 
          -1
          -2
          -3
          -4
          -5
          -6
          -7
          -8
          -9
          -10
          -11
          -12
        stdout:
          -January
          -February
          -March
          -April
          -May
          -June
          -July
          -August
          -September
          -October
          -November
          -December
        exit: 0
        
        
        
        
